FROM node:18-alpine AS build

RUN yarn config set registry https://registry.npmmirror.com
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY .env.production .env.production
COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN yarn build

#---

FROM node:18-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package.json yarn.lock ./
COPY ormconfig.js ./
COPY .env.production .env.production
COPY --from=build /app/dist ./dist

RUN yarn install --production --frozen-lockfile

EXPOSE 5000
CMD ["yarn", "start:prod"]
